ALTER TABLE prospects
  ADD COLUMN likely_service VARCHAR(80) NULL,
  ADD COLUMN city VARCHAR(500) NULL,
  ADD COLUMN icp VARCHAR(80) NULL,
  ADD COLUMN next_action TEXT NULL,
  ADD COLUMN next_action_date DATE NULL,
  ADD COLUMN next_action_time TIME NULL,
  ADD COLUMN next_action_method VARCHAR(255) NULL,
  ADD COLUMN meeting_date DATE NULL,
  ADD COLUMN meeting_time TIME NULL,
  ADD COLUMN meeting_type VARCHAR(255) NULL,
  ADD COLUMN meeting_location VARCHAR(1000) NULL,
  ADD COLUMN meeting_duration INT UNSIGNED NULL,
  ADD COLUMN teams_scheduled BOOLEAN NULL,
  ADD COLUMN teams_join_url VARCHAR(2048) NULL,
  ADD COLUMN est_monthly_revenue DECIMAL(12,2) NULL,
  ADD COLUMN josh_needed BOOLEAN NULL,
  ADD COLUMN status VARCHAR(40) NULL,
  ADD COLUMN legacy_stage VARCHAR(80) NULL,
  ADD COLUMN import_source VARCHAR(30) NULL,
  ADD CONSTRAINT chk_likely_service CHECK (likely_service IS NULL OR likely_service IN ('Managed IT','Managed IT + Security','BII','Project','Other'));
