ALTER TABLE prospects
  ADD COLUMN IF NOT EXISTS street_address VARCHAR(500) NULL AFTER email,
  ADD COLUMN IF NOT EXISTS zip VARCHAR(10) NULL AFTER street_address,
  ADD COLUMN IF NOT EXISTS state VARCHAR(80) NULL AFTER city;
