import {graph} from './graph.js';
import {SharePoint,buildFields,assertNoPending,submitRequest,plainResult} from './sharepoint.js';
import {query,transaction,audit,json} from './db.js';
import {prospect} from './pipeline.js';
import {discovery} from './discovery.js';
import {mvd} from './discovery-rules.js';
import {ownerOnly,integer,choice,fail} from './security.js';
import {lanes} from './config.js';
export const sp=new SharePoint(graph);
const lookupId=email=>email==='alanna@theitguys.us'?process.env.SP_ALANNA_USER_LOOKUP_ID:email==='josh@theitguys.us'?process.env.SP_JOSH_USER_LOOKUP_ID:undefined;
export async function refresh(p){const s=sp.ready();const rows=await query('SELECT * FROM sp_requests WHERE prospect_id=? AND item_id IS NOT NULL',[p.id]);for(const r of rows){const remote=await sp.request(r.item_id);const status=remote.fields[s.maps.requests['Processing Status'].name];const message=remote.fields[s.maps.requests['Result Message'].name]||'';await query('UPDATE sp_requests SET status=?,result_message=? WHERE id=?',[status,message,r.id]);if(status==='Done'&&r.action==='CreateClient'){const client=await sp.client(p);if(client){const id=client.fields[s.maps.clients['Client ID'].name];if(id){await query('UPDATE prospects SET client_id=?,client_item_id=? WHERE id=?',[id,client.id,p.id]);p.client_id=id;p.client_item_id=client.id;}}}}const client=await sp.client(p);if(!client)return null;return Object.fromEntries(['Client ID','Current Stage','Stage Status','Next Action'].map(k=>[k,client.fields[s.maps.clients[k].name]??'Not supplied']));}
export function handoffRoutes(app){
 app.get('/prospects/:id/handoff',async(req,res)=>{const p=await prospect(req.params.id);let client=null,error=null;try{client=await refresh(p);}catch{error='SharePoint status could not be refreshed. Check the connection before acting.';}const d=await discovery(p.id);const schema=sp.cache;const missing=mvd(d.answers);const approved=(await query("SELECT id FROM quotes WHERE prospect_id=? AND status='Approved'",[p.id])).length>0;const ready=!schema.errors.length&&!p.hold;res.render('handoff',{p,client,error,schema,missing,approved,ready,requests:await query('SELECT * FROM sp_requests WHERE prospect_id=? ORDER BY id DESC',[p.id]),json,plainResult,lanes});});
 app.post('/prospects/:id/handoff',async(req,res)=>{const action=choice(req.body.action,['CreateClient','Quoting','TechnicalAssessment']);if(action!=='CreateClient'&&req.session.user.role!=='owner')fail('Owner access required.',403);let body,schema,id;const mode=process.env.SHAREPOINT_WRITE_MODE||'dryrun';await transaction(async c=>{await query('SELECT id FROM prospects WHERE id=? FOR UPDATE',[integer(req.params.id)],c);const p=await prospect(req.params.id,c);if(p.hold)fail('On Hold — Pending Josh Review');schema=sp.ready();if((await query("SELECT id FROM sp_requests WHERE prospect_id=? AND status IN ('Preparing','Pending','Processing','Unknown')",[p.id],c)).length)fail('A request is already active or needs reconciliation.');const lane=choice(action==='CreateClient'?req.body.service_lane:p.service_lane,lanes);const d=await discovery(p.id,c);if(action==='CreateClient'){if(p.client_id)fail('This opportunity already has a SharePoint client.');if(!['Qualified','Discovery','Proposal Sent','Closed Won','Technical Assessment'].includes(p.stage)||mvd(d.answers).length)fail('Qualify the opportunity and complete discovery first.');if(await sp.client(p))fail('A SharePoint client already exists for this opportunity; Josh must reconcile it before resubmission.');}if(action==='Quoting'&&!(await query("SELECT id FROM quotes WHERE prospect_id=? AND status='Approved'",[p.id],c)).length)fail('An Approved quote is required.');try{assertNoPending(await sp.requests(),schema,p);body=buildFields(schema,action,p,lane,req.session.user.email,new Date(),lookupId(req.session.user.email));}catch(e){fail(e.message);}const result=await query('INSERT INTO sp_requests (prospect_id,action,request_json,status) VALUES (?,?,?,?)',[p.id,action,JSON.stringify(body),'Preparing'],c);id=result.insertId;await query('UPDATE prospects SET service_lane=? WHERE id=?',[lane,p.id],c);await audit(c,req.session.user,'prepare handoff','sp_request',id);});try{const result=await submitRequest(graph,mode,schema,body);await query('UPDATE sp_requests SET status=?,item_id=? WHERE id=?',[result.status,result.itemId,id]);}catch{await query("UPDATE sp_requests SET status='Unknown',result_message=? WHERE id=?",['Delivery could not be confirmed. Search the exact Title in SharePoint before any retry.',id]);}res.redirect(`/prospects/${req.params.id}/handoff`);});
 app.get('/prospects/:id/sharepoint-status',async(req,res)=>{const p=await prospect(req.params.id);try{const client=await refresh(p);const requests=await query('SELECT id,status,result_message FROM sp_requests WHERE prospect_id=? ORDER BY id DESC',[p.id]);res.json({client,requests:requests.map(r=>({...r,plain:plainResult(r.status)}))});}catch{res.status(503).json({error:'SharePoint status unavailable. Josh can check the connection in Admin.'});}});
 app.post('/prospects/:id/mark-lost',ownerOnly,(_req,_res)=>fail('Mark Lost is disabled pending owner confirmation of the exact payload.'));
}
